#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://192.168.204.128:8066/argo_dict?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=mycat
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://192.168.204.128:8066/mycatdb
#spring.datasource.username=mycat
#spring.datasource.password=123456
spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.214.147:3306/workdb?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store-password: 13195922677ss
#    key-store: classpath:lyqcd.xyz.jks
#    key-store-type: JKS
#condition:
#  http2https: true
#http:
#  port: 80

server:
  port: 8081
